// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8LhejArzq_XRMs4g8Hv8yc_9PuhTyvA',
    appId: '1:135546039401:web:cd9e453d12df60a6c746f8',
    messagingSenderId: '135546039401',
    projectId: 'sspapp-71608',
    authDomain: 'sspapp-71608.firebaseapp.com',
    storageBucket: 'sspapp-71608.firebasestorage.app',
    measurementId: 'G-D222M75G16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzetP8QnXtxYROq373pF6kHNhvYbYgJ8',
    appId: '1:135546039401:android:a2f9668ffe9e911ec746f8',
    messagingSenderId: '135546039401',
    projectId: 'sspapp-71608',
    storageBucket: 'sspapp-71608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-rMJQd0qnjob_aKgYKDUejYnmTFIvsg',
    appId: '1:135546039401:ios:0a5cd07865f60667c746f8',
    messagingSenderId: '135546039401',
    projectId: 'sspapp-71608',
    storageBucket: 'sspapp-71608.firebasestorage.app',
    iosBundleId: 'com.example.sspaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA-rMJQd0qnjob_aKgYKDUejYnmTFIvsg',
    appId: '1:135546039401:ios:0a5cd07865f60667c746f8',
    messagingSenderId: '135546039401',
    projectId: 'sspapp-71608',
    storageBucket: 'sspapp-71608.firebasestorage.app',
    iosBundleId: 'com.example.sspaap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX8LhejArzq_XRMs4g8Hv8yc_9PuhTyvA',
    appId: '1:135546039401:web:289ec433538d9633c746f8',
    messagingSenderId: '135546039401',
    projectId: 'sspapp-71608',
    authDomain: 'sspapp-71608.firebaseapp.com',
    storageBucket: 'sspapp-71608.firebasestorage.app',
    measurementId: 'G-PWCWDCGWN9',
  );

}